name: Clear GitHub user content cache

on:
    push:
        branches:
            - main # Change this to your main branch name

jobs:
    clear-cache:
        runs-on: ubuntu-latest
        steps:
            - name: purge
            - uses: j-leidy/action-camo-purge@v1
            - name: Run a script
              run: echo This script clears the GitHub user content cache
